### ISSUE TITLE
睡眠后唤醒，显示器显示无信号

### ISSUE THREAD

**Issue by xingkong906** [oldweek/ASUS-TX-B760m-hackintosh#1]
大佬，您好！首先感谢您的付出，让我在使用您的EFi文件成功安装了黑苹果，然后我想咨询一下：
1. 在点击睡眠后，再次唤醒，屏幕无显示，并提示无信号。目前使用的是HDMI接入。
2. 我使用hack tool工具打开后显示目前oc版本是0.99，我EFI选择是您的release下14.4的文件，请帮忙确认下是否是您这边上传错了。

系统信息如下：<img width="290" alt="截屏2024-06-08 12 47 02" src="https://github.com/oldweek/ASUS-TX-B760m-hackintosh/assets/16444239/22ab0634-0918-4ee4-bce3-979ccaf81e3d">
CPU:12600KF
显卡：Vega56
显示器为红米4K 60HZ显示器
针对第一个问题，期待您的答复，我的邮件starrysky108@qq.com，由衷感谢。

**Comment by xingkong906** [comment]
CPU:12600Kf

**Comment by oldweek** [comment]
非常感谢你的反馈，我将需要2天时间对EFI进行测试，另外EFI文件也会进行整合（已经测试出新的兼容性方案，可以使用一个EFI文件兼容多个系统）。
如有更新会通过邮件告知与你，尽请留意。

**Comment by xingkong906** [comment]
好的，感谢。目前是单硬盘安装Windows11+mac14.5

**Comment by xingkong906** [comment]
不小心点关闭了，抱歉

**Comment by oldweek** [comment]
efi文件已经更新

**Comment by xingkong906** [comment]
感谢，我已经直接放进去更新，但目前还是一样的不能唤醒屏幕

**Comment by xingkong906** [comment]
睡眠后，主机会慢慢停止，30左右听到风扇停的声音瞬间又启动，再经过11分钟左右，才能完全关闭。按下键盘触发唤醒，大约在主机活跃1分钟左右，屏幕从全黑开始亮，但显示无信号

**Comment by oldweek** [comment]
有没有尝试使用dp接口？

**Comment by oldweek** [comment]
或者是引入 ： HibernationFixup.kext，这个用来尝试修复睡眠问题

**Comment by oldweek** [comment]
启动项也可以尝试添加 ： igfxonln=1

**Comment by oldweek** [comment]
macOS系统睡眠以后唤醒黑屏无输出，大概率是显卡驱动掉线，由于其他设备并没有出现这种情况，所以具体原因还需要看日志进行分析。

基于这种情况下，给出以下几种处理方案提供参考：

1，尝试在启动项boot-args中添加参数 igfxonln=1，路径为：nvram -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args ,原参数为：agdpmod=pikera alcid=13 修改为 ： agdpmod=pikera alcid=13 igfxonln=1
保存后重启尝试睡眠几分钟进行唤醒。

2，增加 HibernationFixup.kext ，增加这个到 kernel当中，然后尝试睡眠并等待几分钟进行唤醒。

3，如果有dp线的话，可以尝试换dp线使用，并进行睡眠，然后等待几分钟尝试唤醒。

**Comment by oldweek** [comment]
强制驱动在线的配置已经更新，可以尝试使用

**Comment by xingkong906** [comment]
感谢您的帮助，我先进行尝试，如果不成功就等DP线到了之后再进行尝试，预计10号
