### ISSUE TITLE
B760天选D5主板，12600KF的cpu能用吗

### ISSUE THREAD

**Issue by jesonjax** [oldweek/ASUS-TX-B760m-hackintosh#2]

**Comment by chenyinghong** [comment]
同代CPU 都可以  我记得博主也是12代

**Comment by oldweek** [comment]
可以使用，这个处理器的配置文件已经兼容12代跟13代酷睿系列了。

**12600kf是大小核，用这个EFI不需要任何处理器方面的额外设置。**

其他非大小核需要禁用处理器的大小核调度补丁。
