### ISSUE TITLE
6750GRE 能否支持ACPI 显卡仿冒？

### ISSUE THREAD

**Issue by chenyinghong** [oldweek/ASUS-TX-B760m-hackintosh#3]
ACPI信息，增加支持 RX6650XT 与 TX6690XT 显卡的仿冒支持，
能否增加6750GRE ?

**Comment by oldweek** [comment]
6750GRE需要尝试增加 ：NootRX.kext补丁

这是补丁的下载地址 ：https://github.com/ChefKissInc/NootRX/releases/tag/nightly

**Comment by chenyinghong** [comment]
不需要在ACPI 部分增加仿冒之类的吗？

**Comment by oldweek** [comment]
不用，增加这个驱动程序即可

**Comment by chenyinghong** [comment]
谢谢大佬
